name: Zircon Studio Proxy
description: "A proxy for Zircon Studio web application"
version: "1.0.0"
slug: zircon_proxy
panel_title: Zircon Studio
panel_icon: mdi:floor-plan
init: false
ingress: true
ingress_port: 3100
ports:
  3100/tcp: 3100
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  baseUrl: https://zircon.app
  signIn:
    email: null
    password: null
  location:
    group: null
    project: null
  certs:
    key: null
    cert: null
schema:
  baseUrl: url
  signIn:
    email: email
    password: password
  location:
    group: "match(^[a-zA-Z0-9]+$)"
    project: "match(^[a-zA-Z0-9]+$)"
  certs:
    key: "str?"
    cert: "str?"
